'use server';

/**
 * @fileOverview A flow that generates empathetic feedback based on user journal entries and MCQ responses.
 *
 * - generateEmpatheticFeedback - A function that generates empathetic feedback and actionable precautions.
 * - EmpatheticFeedbackInput - The input type for the generateEmpatheticFeedback function.
 * - EmpatheticFeedbackOutput - The return type for the generateEmpatheticFeedback function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EmpatheticFeedbackInputSchema = z.object({
  journalEntry: z.string().describe('The user\'s journal entry for the day.'),
  mcqResponses: z.string().describe('The user\'s responses to the multiple-choice questions.'),
  depressionScore: z.number().describe('The user\'s depression score for the day.'),
  depressionLevel: z.string().describe('The user\'s depression level for the day.'),
});
export type EmpatheticFeedbackInput = z.infer<typeof EmpatheticFeedbackInputSchema>;

const EmpatheticFeedbackOutputSchema = z.object({
  feedback: z.string().describe('The empathetic feedback generated by the AI.'),
  precautions: z.string().describe('Actionable precautions based on the user\'s mental state.'),
});
export type EmpatheticFeedbackOutput = z.infer<typeof EmpatheticFeedbackOutputSchema>;

export async function generateEmpatheticFeedback(
  input: EmpatheticFeedbackInput
): Promise<EmpatheticFeedbackOutput> {
  return generateEmpatheticFeedbackFlow(input);
}

const prompt = ai.definePrompt({
  name: 'empatheticFeedbackPrompt',
  input: {schema: EmpatheticFeedbackInputSchema},
  output: {schema: EmpatheticFeedbackOutputSchema},
  prompt: `You are an AI assistant designed to provide empathetic feedback and actionable precautions based on a user's journal entry, MCQ responses, depression score, and depression level.

Journal Entry: {{{journalEntry}}}
MCQ Responses: {{{mcqResponses}}}
Depression Score: {{{depressionScore}}}
Depression Level: {{{depressionLevel}}}

Provide empathetic feedback that acknowledges the user's feelings and offers encouragement. Also, suggest actionable precautions that the user can take to improve their mental wellbeing.

Format your response as follows:
Feedback: [Empathetic feedback here]
Precautions: [Actionable precautions here]`,
});

const generateEmpatheticFeedbackFlow = ai.defineFlow(
  {
    name: 'generateEmpatheticFeedbackFlow',
    inputSchema: EmpatheticFeedbackInputSchema,
    outputSchema: EmpatheticFeedbackOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
